### ISSUE TITLE
The newline in the response are skipped

### ISSUE THREAD

**Issue by tangye1234** [janlay/openai-cli#2]
I ask it to give me a sql for a specific situation, and it gives me:

`SELECT class, AVG(score) AS avg_score, MAX(score) AS max_score, MIN(score) AS min_scoreFROM student_scoresGROUP BY class;`

Apparently the newline characters are swallowed.

**Comment by janlay** [comment]
Confirmed, WIP.

**Comment by janlay** [comment]
<img width="537" alt="image" src="https://user-images.githubusercontent.com/94615/233795418-3b4ba5c5-4b04-4d55-a18f-bd9183e2d44a.png">

Looks like a bug in BASH. No ETA yet...
