### ISSUE TITLE
Cli output error

### ISSUE THREAD

**Issue by tangye1234** [janlay/openai-cli#4]
```shell
openai Hello
```

It returns:

/usr/local/bin/openai: line 178: ${#chunk}-2: substring expression < 0
curl: (23) Failure writing output to destination

**Comment by tangye1234** [comment]
I think we can use：

```shell
if [ ${#chunk} -gt 2 ]; then
  chunk="${chunk:0:${#chunk}-2}"
else
  chunk=""
fi
```

to ensure the length is greater than 2

**Comment by janlay** [comment]
I haven't reproduced this issue and pushed a new minor update. Thanks for your report though.
