### ISSUE TITLE
Cli model gpt-4 error

### ISSUE THREAD

**Issue by tangye1234** [janlay/openai-cli#5]
```shell
openai +model=gpt-4 hello
```

prints
```
jq: invalid JSON text passed to --argjson
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://stedolan.github.io/jq
```

**Comment by tangye1234** [comment]
I found the issue is in https://github.com/janlay/openai-cli/blob/569079b06baa3dd6fed9135327883428c6cb652c/openai#L71

```shell
[[ $value =~ ^[+-]?\ ?[0-9.]+$ || $value = true || $value = false || $value =~ ^[\[\{]* ]] && arg=--argjson
```

The `+model=gpt-4` args will infer $value=gpt-4 which actually matches `^[\[\{]*`

but it should use `--arg` not `--argjson`
The resolution should be use `^[\[\{]+` instead of `^[\[\{]*`

**Comment by janlay** [comment]
It's confirmed and was fixed right now. Thanks for continuously reporting bugs 💯
