### ISSUE TITLE
jq depreciated --argfile

### ISSUE THREAD

**Issue by arch-btw** [janlay/openai-cli#7]
Hi,

Thank you for this nice project!

Please see: https://github.com/jqlang/jq/pull/2768

Output when using openai-cli:

> jq: Unknown option --argfile
Use jq --help for help with command-line options,
or see the jq manpage, or online docs  at https://jqlang.github.io/jq

**Comment by janlay** [comment]
Thanks for the info, sorry the fix is a bit late 😂
