### ISSUE TITLE
Temp directories are not cleaned up

### ISSUE THREAD

**Issue by dhuertas42** [janlay/openai-cli#8]
The script leaves behind a trail of temporary folders. It seems to me it is not removing them in the `cleanup()` function that runs on EXIT. I suspect it needs `&&` after checking the directory exists in `[ -d "$temp_dir" ] || rm -f -- "$temp_dir"`, instead of `||`.

![image](https://github.com/janlay/openai-cli/assets/144000595/0ccb4702-9ee5-4646-ad25-e9d0c81bbbe4)

**Comment by janlay** [comment]
There is a mistake. Thanks for providing detailed description of the issue.
