### ISSUE TITLE
Config file in home directory

### ISSUE THREAD

**Issue by bmomjian** [janlay/openai-cli#9]
It would be nice if you could define configuration variables in a configuration file, rather than just in the environment.  If you add this line near the top of the script:

          `[ -e "$HOME"/.openai/config ] && . "$HOME"/.openai/config

it will allow such a usage.  I had to move the OPENAI_DATA_DIR above the config file load, and the config file load had to be before the environment variable usage.  I added documentation too.

**Comment by janlay** [comment]
Very great advice and PR implementation, thanks!
